# Site settings
title: Bruno Konrad
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brunoskonrad.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jemoji
